#!/bin/bash

REGISTRY=quay.io/dev-talk
IMAGE_NAME=votebot

docker build --tag "$IMAGE_NAME" .
if [ "$TRAVIS_BRANCH" == "development" ]; then
    docker tag "${IMAGE_NAME}" "${IMAGE_NAME}:development"
    docker tag "${IMAGE_NAME}" "${IMAGE_NAME}:development-${TRAVIS_COMMIT}"
    docker push "${REGISTRY}/${IMAGE_NAME}"
elif [ "$1" == "master" ] && [ -n "$TRAVIS_TAG" ]; then
    docker tag "${IMAGE_NAME}" "${IMAGE_NAME}:latest"
    docker tag "${IMAGE_NAME}" "${IMAGE_NAME}:${TRAVIS_TAG}"
    docker push "${REGISTRY}/${IMAGE_NAME}"
fi
